# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hekapoo/Documents/openglStuff/cmake_stuff

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hekapoo/Documents/openglStuff/cmake_stuff

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hekapoo/Documents/openglStuff/cmake_stuff/CMakeFiles /home/hekapoo/Documents/openglStuff/cmake_stuff/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hekapoo/Documents/openglStuff/cmake_stuff/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named openGL_UI

# Build rule for target.
openGL_UI: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openGL_UI
.PHONY : openGL_UI

# fast build rule for target.
openGL_UI/fast:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/build
.PHONY : openGL_UI/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/main.cpp.s
.PHONY : main.cpp.s

src/Buffers/Ibo.o: src/Buffers/Ibo.cpp.o

.PHONY : src/Buffers/Ibo.o

# target to build an object file
src/Buffers/Ibo.cpp.o:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Buffers/Ibo.cpp.o
.PHONY : src/Buffers/Ibo.cpp.o

src/Buffers/Ibo.i: src/Buffers/Ibo.cpp.i

.PHONY : src/Buffers/Ibo.i

# target to preprocess a source file
src/Buffers/Ibo.cpp.i:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Buffers/Ibo.cpp.i
.PHONY : src/Buffers/Ibo.cpp.i

src/Buffers/Ibo.s: src/Buffers/Ibo.cpp.s

.PHONY : src/Buffers/Ibo.s

# target to generate assembly for a file
src/Buffers/Ibo.cpp.s:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Buffers/Ibo.cpp.s
.PHONY : src/Buffers/Ibo.cpp.s

src/Buffers/Vao.o: src/Buffers/Vao.cpp.o

.PHONY : src/Buffers/Vao.o

# target to build an object file
src/Buffers/Vao.cpp.o:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Buffers/Vao.cpp.o
.PHONY : src/Buffers/Vao.cpp.o

src/Buffers/Vao.i: src/Buffers/Vao.cpp.i

.PHONY : src/Buffers/Vao.i

# target to preprocess a source file
src/Buffers/Vao.cpp.i:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Buffers/Vao.cpp.i
.PHONY : src/Buffers/Vao.cpp.i

src/Buffers/Vao.s: src/Buffers/Vao.cpp.s

.PHONY : src/Buffers/Vao.s

# target to generate assembly for a file
src/Buffers/Vao.cpp.s:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Buffers/Vao.cpp.s
.PHONY : src/Buffers/Vao.cpp.s

src/Buffers/Vbo.o: src/Buffers/Vbo.cpp.o

.PHONY : src/Buffers/Vbo.o

# target to build an object file
src/Buffers/Vbo.cpp.o:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Buffers/Vbo.cpp.o
.PHONY : src/Buffers/Vbo.cpp.o

src/Buffers/Vbo.i: src/Buffers/Vbo.cpp.i

.PHONY : src/Buffers/Vbo.i

# target to preprocess a source file
src/Buffers/Vbo.cpp.i:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Buffers/Vbo.cpp.i
.PHONY : src/Buffers/Vbo.cpp.i

src/Buffers/Vbo.s: src/Buffers/Vbo.cpp.s

.PHONY : src/Buffers/Vbo.s

# target to generate assembly for a file
src/Buffers/Vbo.cpp.s:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Buffers/Vbo.cpp.s
.PHONY : src/Buffers/Vbo.cpp.s

src/Primitives/Quad.o: src/Primitives/Quad.cpp.o

.PHONY : src/Primitives/Quad.o

# target to build an object file
src/Primitives/Quad.cpp.o:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Primitives/Quad.cpp.o
.PHONY : src/Primitives/Quad.cpp.o

src/Primitives/Quad.i: src/Primitives/Quad.cpp.i

.PHONY : src/Primitives/Quad.i

# target to preprocess a source file
src/Primitives/Quad.cpp.i:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Primitives/Quad.cpp.i
.PHONY : src/Primitives/Quad.cpp.i

src/Primitives/Quad.s: src/Primitives/Quad.cpp.s

.PHONY : src/Primitives/Quad.s

# target to generate assembly for a file
src/Primitives/Quad.cpp.s:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Primitives/Quad.cpp.s
.PHONY : src/Primitives/Quad.cpp.s

src/Scene/Scene.o: src/Scene/Scene.cpp.o

.PHONY : src/Scene/Scene.o

# target to build an object file
src/Scene/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Scene/Scene.cpp.o
.PHONY : src/Scene/Scene.cpp.o

src/Scene/Scene.i: src/Scene/Scene.cpp.i

.PHONY : src/Scene/Scene.i

# target to preprocess a source file
src/Scene/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Scene/Scene.cpp.i
.PHONY : src/Scene/Scene.cpp.i

src/Scene/Scene.s: src/Scene/Scene.cpp.s

.PHONY : src/Scene/Scene.s

# target to generate assembly for a file
src/Scene/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Scene/Scene.cpp.s
.PHONY : src/Scene/Scene.cpp.s

src/Scene/Types/ISceneElement.o: src/Scene/Types/ISceneElement.cpp.o

.PHONY : src/Scene/Types/ISceneElement.o

# target to build an object file
src/Scene/Types/ISceneElement.cpp.o:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Scene/Types/ISceneElement.cpp.o
.PHONY : src/Scene/Types/ISceneElement.cpp.o

src/Scene/Types/ISceneElement.i: src/Scene/Types/ISceneElement.cpp.i

.PHONY : src/Scene/Types/ISceneElement.i

# target to preprocess a source file
src/Scene/Types/ISceneElement.cpp.i:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Scene/Types/ISceneElement.cpp.i
.PHONY : src/Scene/Types/ISceneElement.cpp.i

src/Scene/Types/ISceneElement.s: src/Scene/Types/ISceneElement.cpp.s

.PHONY : src/Scene/Types/ISceneElement.s

# target to generate assembly for a file
src/Scene/Types/ISceneElement.cpp.s:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Scene/Types/ISceneElement.cpp.s
.PHONY : src/Scene/Types/ISceneElement.cpp.s

src/Scene/Types/Panel.o: src/Scene/Types/Panel.cpp.o

.PHONY : src/Scene/Types/Panel.o

# target to build an object file
src/Scene/Types/Panel.cpp.o:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Scene/Types/Panel.cpp.o
.PHONY : src/Scene/Types/Panel.cpp.o

src/Scene/Types/Panel.i: src/Scene/Types/Panel.cpp.i

.PHONY : src/Scene/Types/Panel.i

# target to preprocess a source file
src/Scene/Types/Panel.cpp.i:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Scene/Types/Panel.cpp.i
.PHONY : src/Scene/Types/Panel.cpp.i

src/Scene/Types/Panel.s: src/Scene/Types/Panel.cpp.s

.PHONY : src/Scene/Types/Panel.s

# target to generate assembly for a file
src/Scene/Types/Panel.cpp.s:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Scene/Types/Panel.cpp.s
.PHONY : src/Scene/Types/Panel.cpp.s

src/Shaders/Shader.o: src/Shaders/Shader.cpp.o

.PHONY : src/Shaders/Shader.o

# target to build an object file
src/Shaders/Shader.cpp.o:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Shaders/Shader.cpp.o
.PHONY : src/Shaders/Shader.cpp.o

src/Shaders/Shader.i: src/Shaders/Shader.cpp.i

.PHONY : src/Shaders/Shader.i

# target to preprocess a source file
src/Shaders/Shader.cpp.i:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Shaders/Shader.cpp.i
.PHONY : src/Shaders/Shader.cpp.i

src/Shaders/Shader.s: src/Shaders/Shader.cpp.s

.PHONY : src/Shaders/Shader.s

# target to generate assembly for a file
src/Shaders/Shader.cpp.s:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Shaders/Shader.cpp.s
.PHONY : src/Shaders/Shader.cpp.s

src/Window/Input.o: src/Window/Input.cpp.o

.PHONY : src/Window/Input.o

# target to build an object file
src/Window/Input.cpp.o:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Window/Input.cpp.o
.PHONY : src/Window/Input.cpp.o

src/Window/Input.i: src/Window/Input.cpp.i

.PHONY : src/Window/Input.i

# target to preprocess a source file
src/Window/Input.cpp.i:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Window/Input.cpp.i
.PHONY : src/Window/Input.cpp.i

src/Window/Input.s: src/Window/Input.cpp.s

.PHONY : src/Window/Input.s

# target to generate assembly for a file
src/Window/Input.cpp.s:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Window/Input.cpp.s
.PHONY : src/Window/Input.cpp.s

src/Window/Time.o: src/Window/Time.cpp.o

.PHONY : src/Window/Time.o

# target to build an object file
src/Window/Time.cpp.o:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Window/Time.cpp.o
.PHONY : src/Window/Time.cpp.o

src/Window/Time.i: src/Window/Time.cpp.i

.PHONY : src/Window/Time.i

# target to preprocess a source file
src/Window/Time.cpp.i:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Window/Time.cpp.i
.PHONY : src/Window/Time.cpp.i

src/Window/Time.s: src/Window/Time.cpp.s

.PHONY : src/Window/Time.s

# target to generate assembly for a file
src/Window/Time.cpp.s:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Window/Time.cpp.s
.PHONY : src/Window/Time.cpp.s

src/Window/Window.o: src/Window/Window.cpp.o

.PHONY : src/Window/Window.o

# target to build an object file
src/Window/Window.cpp.o:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Window/Window.cpp.o
.PHONY : src/Window/Window.cpp.o

src/Window/Window.i: src/Window/Window.cpp.i

.PHONY : src/Window/Window.i

# target to preprocess a source file
src/Window/Window.cpp.i:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Window/Window.cpp.i
.PHONY : src/Window/Window.cpp.i

src/Window/Window.s: src/Window/Window.cpp.s

.PHONY : src/Window/Window.s

# target to generate assembly for a file
src/Window/Window.cpp.s:
	$(MAKE) -f CMakeFiles/openGL_UI.dir/build.make CMakeFiles/openGL_UI.dir/src/Window/Window.cpp.s
.PHONY : src/Window/Window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... openGL_UI"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Buffers/Ibo.o"
	@echo "... src/Buffers/Ibo.i"
	@echo "... src/Buffers/Ibo.s"
	@echo "... src/Buffers/Vao.o"
	@echo "... src/Buffers/Vao.i"
	@echo "... src/Buffers/Vao.s"
	@echo "... src/Buffers/Vbo.o"
	@echo "... src/Buffers/Vbo.i"
	@echo "... src/Buffers/Vbo.s"
	@echo "... src/Primitives/Quad.o"
	@echo "... src/Primitives/Quad.i"
	@echo "... src/Primitives/Quad.s"
	@echo "... src/Scene/Scene.o"
	@echo "... src/Scene/Scene.i"
	@echo "... src/Scene/Scene.s"
	@echo "... src/Scene/Types/ISceneElement.o"
	@echo "... src/Scene/Types/ISceneElement.i"
	@echo "... src/Scene/Types/ISceneElement.s"
	@echo "... src/Scene/Types/Panel.o"
	@echo "... src/Scene/Types/Panel.i"
	@echo "... src/Scene/Types/Panel.s"
	@echo "... src/Shaders/Shader.o"
	@echo "... src/Shaders/Shader.i"
	@echo "... src/Shaders/Shader.s"
	@echo "... src/Window/Input.o"
	@echo "... src/Window/Input.i"
	@echo "... src/Window/Input.s"
	@echo "... src/Window/Time.o"
	@echo "... src/Window/Time.i"
	@echo "... src/Window/Time.s"
	@echo "... src/Window/Window.o"
	@echo "... src/Window/Window.i"
	@echo "... src/Window/Window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

